# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sofar_procrustes_RCpp <- function(XY, XX, D, rho2, U, control) {
    .Call('sofar_sofar_procrustes_RCpp', PACKAGE = 'sofar', XY, XX, D, rho2, U, control)
}

kron_RcppArma <- function(A, B) {
    .Call('sofar_kron_RcppArma', PACKAGE = 'sofar', A, B)
}

